#!/bin/bash

# at the moment, the script works only for
# generate probed velocities for points in probesDict with field magU
# and starting time at 40 seconds. That means,
# it reads explicitly from postProcessing/probes/40/magU
#
# to do: -read from first time in postProcessing/probes
#		-read from field to probe
echo -e "\n"
echo "sample for velocity probes evaluation"

#probeLocations

###Mittelwert pro spalte

## Erstellen eines Diagramms mit GnuPlot

echo "ploting diagram"
gnuplot <<- EOF

    set terminal pngcairo size 1600,600 enhanced font 'Verdana,10'
    set title 'Velocity probe on selected points'
	set xlabel 'time [s]'
    set ylabel 'velocity [m/s]'
    set grid
	outfile = 'postProcessing/velocityProbes/velocity_diagram.png'
	set output outfile

	# plot file generated by probeLocations, to fix: get the points from header
	set key outside
	plot for [i=2:5] 'postProcessing/probes/40/magU' using 1:i with linespoints title 'point '.(i-1) #columnheader(i)

	print 'Plot image generated in: '.outfile

	#points = system('cat points_coord')
	#item(n) = word(points,n)

	# get the mean for each point and print it to a file StatDat.dat
	#set print "StatDat.dat"
	#do for [i=2:words(points)+1] {
	#  stats  'postProcessing/velocityProbes/table_velocity' u i nooutput ;
	#  print STATS_mean
	#}
	#set print

	#set key outside
	#plot for [col=2:words(points)+1] 'postProcessing/velocityProbes/table_velocity' using 1:col with linespoints title item(col-1)

	#to fix: get mean values to plot as a line
	#	-delete StatDat.data file
	#plot for [col=2:words(points)+1] 'postProcessing/velocityProbes/table_velocity' using 1:col with linespoints title item(col-1), \
	#	for [col=1:words(points)] 'StatDat.dat' using 1:col with lines title col
EOF
