#!/bin/bash

# at the moment, the script works only for
# generate probed velocities for points in probesDict with field magU
# and starting time at 40 seconds. That means,
# it reads explicitly from postProcessing/probes/40/magU
#
# to do: -read from first time in postProcessing/probes
#		-read from field to probe
echo -e "\n"
echo "sample for velocity probes evaluation"

#probeLocations

## Erstellen eines Diagramms mit GnuPlot

echo "ploting diagram"
gnuplot <<- EOF

    set terminal pngcairo size 1600,600 enhanced font 'Verdana,10'
    set title 'Velocity probe on selected points'
	set xlabel 'time [s]'
    set ylabel 'velocity [m/s]'
    set grid
	outfile = 'postProcessing/velocityProbes/velocity_diagram.png'
	set output outfile

	# plot file generated by probeLocations, to fix:
	# - get the points from header
	# - get the number of points
	set key outside
	numOfPoints = 4
	firstTimeDir = 40

	###MITTELWERT
	# get the mean for each point and print it to a file StatDat.dat
	set print "StatDat.dat"
	do for [i=2:numOfPoints+1] {
	  stats  'postProcessing/probes/'.firstTimeDir.'/magU' u i nooutput ;
	  print STATS_mean
	}
	set print

	# transpose StatDat.dat file and append it to the probed files (slow, but for the moment the only solution :( )
	system('> meanValues; while IFS= read line; do cut -f1 StatDat.dat | paste -s >> meanValues; done < postProcessing/probes/40/magU')
	system('paste postProcessing/probes/40/magU meanValues > dataToPlot')

	plot for [i=2:numOfPoints+1] 'dataToPlot' using 1:i with linespoints title 'point '.(i-1),\
		for [i=numOfPoints+2:(numOfPoints*2)+1] 'dataToPlot' using 1:i with lines title 'mean velocity point '.(i-numOfPoints-1)

	print 'Plot image generated in: '.outfile
EOF
rm StatDat.dat meanValues dataToPlot
